---
name: wordpress
director_uuid: BOSH_DIRECTOR_UUID

release:
  name: wordpress
  version: 1

compilation:
  workers: 10 # only the required number are provisioned
  network: default
  cloud_properties:
    instance_type: m1.small

# this section describes how updates are handled
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
      - default
  - name: nginx_network
    type: vip
    cloud_properties:
      security_groups:
      - default
  - name: wordpress_network
    type: vip
    cloud_properties:
      security_groups:
      - default
  - name: mysql_network
    type: vip
    cloud_properties:
      security_groups:
      - default

resource_pools:
  - name: common
    network: default
    size: 3
    stemcell:
      name: bosh-stemcell
      version: 0.6.2
    cloud_properties:
      instance_type: m1.small
      availability_zone:
      key_name: 

jobs:
  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
    - name: nginx_network
      default: [dns, gateway]
      static_ips:
      - NGINX_ELASTICIP
  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: common
    networks:
    - name: wordpress_network
      default: [dns, gateway]
      static_ips:
      - WORDPRESS_ELASTICIP
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: common
    persistent_disk: 16384
    networks:
    - name: mysql_network
      default: [dns, gateway]
      static_ips:
      - MYSQL_ELASTICIP

properties:
  nginx:
    workers: 1
  wordpress:
    admin: foo@bar.com
    port: 8008
    servers:
      - WORDPRESS_ELASTICIP
    servername: NGINX_SERVERNAME
    db:
      name: wp
      user: wordpress
      pass: w0rdpr3ss
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key
  mysql:
    address: MYSQL_ELASTICIP
    port: 3306
    password: rootpass
