---
roles:
  - blobstore:    PUBLIC_DNS_NAME
  - nats:         PUBLIC_DNS_NAME
  - postgresql:   PUBLIC_DNS_NAME
  - redis:        PUBLIC_DNS_NAME
  - director:     PUBLIC_DNS_NAME
  - aws_registry: PUBLIC_DNS_NAME
user: ubuntu
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
chef_node:
  director:
    runner: root
    aws:
      access_key_id:     ACCESS_KEY_ID
      secret_access_key: SECRET_ACCESS_KEY
      default_key_name: fog_default
      default_security_groups: ["default"]
      ec2_endpoint: ec2.us-east-1.amazonaws.com
      max_retries: 2
  aws_registry:
    endpoint: http://admin:admin@PUBLIC_DNS_NAME:25777
    http:
      user: admin
      password: admin